# Generated by Django 4.2.1 on 2023-05-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('GPA', models.FloatField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('level', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70)),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
    ]
